### ISSUE TITLE
Add EU and other coutry groups

### ISSUE THREAD

**Issue by hildogjr** [deactivated/python-iso3166#15]
It will be interesting to have a method that return the countries that belong to some group. E.g.

    iso3166.Group('EU')
    >> ['AT', 'BE', 'BG', 'CY', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'HU', 'HR', 'IE', 'IT', 'LT', 'LU', 'LV', 'MT', 'NL', 'PL', 'PT', 'RO', 'SE', 'SI', 'SK']

Also some method to return the group(s) that the country belongs:

   iso3166.ThemGroups('IT')
   >> ['EU']

**Comment by deactivated** [comment]
Thanks for the suggestion. This is an interesting idea, but I think it's out of scope for this project.
