### ISSUE TITLE
Kosovo 000 - Seems illegitimate 

### ISSUE THREAD

**Issue by betaboon** [deactivated/python-iso3166#18]
Hello @deactivated ,
You have recently assigned `000`-numeric for kosovo.

First of all: thanks for assigning a numeric value.

But:
The usage of `000` seems wrong, as iso3166 clearly states the user-defined range as `900 to 999`.[[1]](https://www.iso.org/glossary-for-iso-3166.html)
We have been using `999` internally for the time being.
The national statistical office of canada uses `983`.[[2]](https://www.statcan.gc.ca/eng/subjects/standard/sccai/2011/scountry-desc)

I would very much prefer not using `0` but any value in the officially provided user-defined range.

**Comment by deactivated** [comment]
Hi @betaboon,

Thanks for pointing this out. I agree that it makes sense to pick something in the 900 range, and it seems unlikely that anyone is depending on the current behavior. I'll switch the value to 983, which seems as reasonable as anything else.
