### ISSUE TITLE
Suggestion: simple support for other country code systems when feasible

### ISSUE THREAD

**Issue by ajmyyra** [deactivated/python-iso3166#23]
Hi there,

Thank you for creating and maintaining this project! It's been a lifesaver in productivity for me and certainly many others as well.

I stumbled upon a problem in my own code where user had used UAE for United Arab Emirates instead of ARE and it was accepted since another system knew of this code. UAE is a curious case as every other country code system (as well as their official usage) refers to them as that instead of ARE, so the mistake is understandable. Upon further inspection I noticed that there are a few other similar cases (URY, VAT and VNM to name a few) where the codes differ.

It isn't in the core scope of this project, but for usability it might be good to support either a common other country code or a country code from specified other system (UNDP for example). I can create a PR for adding this, but wanted to ask your opinion on such modifications first.

**Comment by akx** [comment]
https://en.wikipedia.org/wiki/Lists_of_country_codes would probably be a good starting point, though I'd say that'd be more of a `country_codes` project than `iso3166` :)

* [x] List of ISO country codes (ISO 3166)
* [ ] ITU: List of country calling codes E.164
* [ ] ITU: Mobile country code E.212
* [ ] ITU: Maritime identification digits
* [ ] ITU: List of ITU letter codes (radiocommunication division)
* [ ] UIC country code (International Union of Railways)
* [ ] List of GS1 country codes
* [ ] List of NATO country codes
* [ ] List of IOC country codes (International Olympic Committee)
* [ ] List of FIFA country codes (International Federation of Association Football)
* [ ] List of FIPS country codes
* [ ] List of license plate codes

**Comment by molten-firescar96** [comment]
I would prefer if this project, python-iso3166 continued to only support iso3166 codes.
